name: Build CI Worker Image

on:
  workflow_dispatch:

  push:
    paths:
      - infrastructure/images/ci-runner/**


jobs:

  build:

    name: Build CI Worker

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Docker Info
        run: |
          docker version
          docker info


      - name: Build CI Worker Image
        run: |
          docker build \
            -t aiassistant-ci:test \
            infrastructure/images/ci-runner


      - name: Test CI Worker Image
        run: |
          docker run --rm aiassistant-ci:test sh -c "
            python --version &&
            uv --version &&
            jq --version &&
            yq --version
          "

      - name: Login to Local Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | \
          docker login registry.local.test \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin


      - name: Tag CI Worker Image
        run: |
          docker tag \
            aiassistant-ci:test \
            registry.local.test/aiassistant/ci-runner:0.1.0


      - name: Push CI Worker Image
        run: |
          docker push \
            registry.local.test/aiassistant/ci-runner:0.1.0


      - name: Complete
        run: |
          echo "CI worker image build successful"