name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r delivery/requirements.txt
      - run: pip install -e delivery/
      - run: delivery test unit --coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r delivery/requirements.txt
      - run: delivery doctor
