"""
Compiler — promotes a prompt skill to a reusable code module (Tier 1).

Tier 1 ("code") generates a thin, importable Python wrapper module that exposes
a uniform `run(context, *, role=None)` callable. The wrapper delegates to
`skill_runtime.run_skill`, which performs the same compose-prompt + LLM-runtime
steps the interpreter does today. This makes a skill a stable, reusable,
importable code module callable from many workflows, while the original prompt
spec is retained as the source of truth.

Tier 2 ("distilled") — an LLM-generated deterministic implementation — is a
future phase, gated by tests before promotion. See ai-orchestration-design.md.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from registry import Registry


_TEMPLATE = (
    "# Auto-generated by workflow-runner Compiler (Tier 1 wrapper).\n"
    "# Source skill: {NAME}\n"
    "# Regenerate with compile_skill('{NAME}'). Do not edit by hand.\n"
    "from skill_runtime import run_skill\n"
    "\n"
    "\n"
    "def run(context=None, *, role=None):\n"
    "    return run_skill('{NAME}', context or {{}}, role=role)\n"
)


def _module_filename(skill_name: str) -> str:
    """Sanitise a skill name into a valid, unique Python module filename."""
    sanitised = "".join(c if c.isalnum() or c == "_" else "_" for c in skill_name)
    return f"skill_{sanitised}.py"


def compile_skill(
    registry: Registry,
    name: str,
    compiled_dir: Optional[str] = None,
) -> Path:
    """
    Compile a prompt skill into a reusable code module.

    Args:
        registry: The catalog (used to look up and update the skill record).
        name: Skill name to compile.
        compiled_dir: Directory for generated modules. Defaults to a
            ``_compiled`` subdirectory next to the skill spec.

    Returns:
        Path to the generated module file.

    Raises:
        KeyError: If the skill is not registered.
    """
    rec = registry.get_skill(name)  # raises KeyError if missing

    if (
        rec.implementation == "code"
        and rec.module_path
        and Path(rec.module_path).exists()
    ):
        return Path(rec.module_path)  # idempotent: already compiled

    if compiled_dir is None:
        base = Path(rec.spec_path).parent if rec.spec_path else Path.cwd()
        compiled_dir = base / "_compiled"

    target = Path(compiled_dir)
    target.mkdir(parents=True, exist_ok=True)
    module_path = target / _module_filename(name)
    module_path.write_text(_TEMPLATE.replace("{NAME}", name))

    registry.set_implementation(name, "code", module_path=str(module_path))
    return module_path
