"""
Skill Runtime — the canonical, tier-agnostic skill execution entry point.

A compiled skill module (generated by compiler.py) calls `run_skill(name,
context, role=...)`, which performs the same compose-prompt + LLM-runtime steps
that the interpreter (`handlers/skill_handler.py`) does today. Centralising this
here means both the interpreted path and the compiled path share one
implementation, satisfying the Skill Module Interface pattern from
ai-orchestration-design.md.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from composer import compose_skill_prompt
from models import Step, StepType, WorkflowDefinition


def run_skill(
    name: str,
    context: Optional[Dict[str, Any]] = None,
    *,
    role: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Execute a skill by name.

    Args:
        name: Skill name (resolves to its spec via the composer's search paths).
        context: Workflow context (inputs, previous step outputs).
        role: Optional role override for prompt composition.

    Returns:
        The runtime result dict (e.g. ``{"status": "completed", "output": ...}``).
    """
    step = Step(type=StepType.SKILL, name=name, uses=name)
    workflow = WorkflowDefinition(name=name, steps=[step])
    prompt = compose_skill_prompt(step, workflow, context or {}, role)

    from runtime_client import run as runtime_run

    return runtime_run(prompt)
