name: Promote

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Git SHA to promote"
        required: true
      source:
        description: "Source environment"
        required: true
        default: "dev"
      target:
        description: "Target environment"
        required: true
        default: "live"

jobs:
  promote:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r delivery/requirements.txt
      - run: pip install -e delivery/
      - run: delivery promote ${{ github.event.inputs.source }} ${{ github.event.inputs.target }} ${{ github.event.inputs.release }}
      - run: delivery validate ${{ github.event.inputs.target }}
