-- +goose Up
-- ====================================================================
-- PHASE 1: CORE APP SYSTEM DATA LAYOUT
-- ====================================================================
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NULL,
    display_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- PHASE 2: POLYMORPHIC TAXONOMY ENGINE
-- ====================================================================
CREATE TABLE IF NOT EXISTS entity_registry (
    entity_type VARCHAR(50) PRIMARY KEY,
    description TEXT NOT NULL,
    mcp_routing_key VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS attribute_registry (
    id SERIAL PRIMARY KEY,
    entity_type VARCHAR(50) REFERENCES entity_registry(entity_type) ON DELETE CASCADE,
    attribute_name VARCHAR(50) NOT NULL,
    data_type VARCHAR(20) NOT NULL,
    is_required BOOLEAN DEFAULT FALSE,
    UNIQUE(entity_type, attribute_name)
);

CREATE TABLE IF NOT EXISTS generic_entity_store (
    id SERIAL PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL REFERENCES entity_registry(entity_type),
    tenant_id VARCHAR(50) NOT NULL,
    data_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_generic_entity_data ON generic_entity_store USING gin (data_json);
CREATE INDEX IF NOT EXISTS idx_generic_entity_lookup ON generic_entity_store (tenant_id, entity_type);

-- ====================================================================
-- PHASE 4: CHAT MEMORY (Added)
-- ====================================================================
CREATE TABLE IF NOT EXISTS chat_memory (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'assistant',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- PHASE 3: TAXONOMY SEED CONSTANTS
-- ====================================================================
INSERT INTO entity_registry (entity_type, description, mcp_routing_key) VALUES 
('profile', 'Client context metadata framework containing ADHD focus parameters.', 'LIFECYCLE'),
('lead', 'Prospective business targets.', 'PIPELINE'),
('signal', 'Real-time user triggers.', 'PIPELINE'),
('content', 'Outreach texts and templates.', 'PIPELINE')
ON CONFLICT (entity_type) DO NOTHING;

-- +goose Down
DROP TABLE IF EXISTS chat_memory;
DROP INDEX IF EXISTS idx_generic_entity_lookup;
DROP INDEX IF EXISTS idx_generic_entity_data;
DROP TABLE IF EXISTS generic_entity_store;
DROP TABLE IF EXISTS attribute_registry;
DROP TABLE IF EXISTS entity_registry;
DROP TABLE IF EXISTS users;