FROM langchain/langgraph-api:3.11

WORKDIR /app

# Copy the contents of your 'src' directory into the container's /app directory
COPY ./src /app

# Commenting this out until we actually create a requirements.txt
# RUN pip install -r requirements.txt